# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PetClump' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PetClump
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseUI'
  pod 'FirebaseUI/Auth'
  pod 'GoogleSignIn'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Facebook'
  platform :ios, '11.0'
  pod 'FBSDKLoginKit'
  use_frameworks!

  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
    end
  end
end

end
