# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PetClump' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PetClump
  pod 'Firebase/Core'
  pod 'FirebaseUI'
  pod 'FirebaseUI/Auth'

  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Facebook'
  platform :ios, '11.0'


end
